config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'columns#index'
  resources :columns, only: [:index] do
    collection do
      get 'search'
    end
  end

  namespace :admin do
    resources :columns, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :records
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/column.rb
class Column < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :user

  # 空の投稿を保存できないようにする
  validates :title, :text, :genre_id, presence: true

  # ジャンルの選択が「--」の時は保存できないようにする →初期値設定へ変更のためコメントアウト
  # validates :genre_id, numericality: { other_than: 1, message: ' を選択してください ' }
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    # { id: 1, name: '--' }, 初期値へ置き換える
    { id: 2, name: '心不全とは' },
    { id: 3, name: '症状の観察方法' },
    { id: 4, name: '受診の目安' },
    { id: 5, name: '体重管理' },
    { id: 6, name: '飲水・食事' },
    { id: 7, name: '排便' },
    { id: 8, name: '入浴' },
    { id: 9, name: '運動・性' },
    { id: 10, name: '内服' },
    { id: 11, name: '風邪や感染症との関連' },
    { id: 12, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :columns
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :kt, length: { maximum: 4 }
    validates :pulse, length: { maximum: 3 }
    validates :systolic, length: { maximum: 3 }
    validates :diastolic, length: { maximum: 3 }
    validates :bw, length: { maximum: 5 }
    validates :start_time
  end

  # boolean型の場合、真偽値なのでtrueもfalseも入力されるため presence: true は使えない
  validates :palpitation, inclusion: [true, false]
  validates :suffocation, inclusion: [true, false]
  validates :swelling, inclusion: [true, false]
  validates :fatigue, inclusion: [true, false]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :columns
  has_many :records

  with_options presence: true do
    validates :nickname, length: { maximum: 6 }
    validates :target_weight, length: { maximum: 5 }, numericality: true # 数値で入力（小数点含む）
    validates :age, length: { maximum: 3 }, numericality: { only_integer: true }  # 整数のみ
  end
  with_options presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'は全角カタカナを使用してください' } do
    validates :last_name_kana
    validates :first_name_kana
  end

  validates :water_restriction, length: { maximum: 4 }, numericality: { only_integer: true, allow_nil: true }
end

app/controllers/admin/columns_controller.rb
class Admin::ColumnsController < ApplicationController
  # ログインしていないuserがURL入力で操作しようとした場合、ログイン画面に遷移する
  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update]
  # ログインしていても、管理者以外はトップページに遷移する
  before_action :if_not_admin
  before_action :set_column, only: [:edit, :update]

  # 以下に管理者が行うアクションを記載
  def new
    @column = Column.new
  end

  def create
    @column = Column.new(column_params)
    if @column.valid?
      @column.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @column.update(column_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    column = Column.find(params[:id])
    column.destroy
    redirect_to root_path
  end

  private

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def column_params
    params.require(:column).permit(:title, :text, :genre_id).merge(user_id: current_user.id)
  end

  def set_column
    @column = Column.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :last_name_kana, :first_name_kana, :target_weight, :age,
                                             :water_restriction])
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  # 最新投稿から順に表示する
  def index
    @columns = Column.includes(:user).order('created_at DESC')
  end

  def search
    @q = Column.ransack(params[:q])
    @columns = @q.result.order('created_at DESC')
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # ログインしていないuserがURL入力で操作しようとした場合、ログイン画面に遷移する
  before_action :authenticate_user!
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  def index
    @records = Record.all
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.valid?
      @record.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @record.update(record_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @record.destroy
    redirect_to root_path
  end

  private

  def record_params
    params.require(:record).permit(:kt, :pulse, :systolic, :diastolic, :bw, :palpitation, :suffocation, :swelling, :fatigue,
                                   :start_time).merge(user_id: current_user.id)
  end

  def set_record
    @record = Record.find(params[:id])
  end
end

app/helpers/admin/columns_helper.rb
module Admin::ColumnsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/admin/columns/edit.html.erb
<%= render "shared/second_header" %>
<%= form_with url: admin_column_path, model: @column, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="column-box">
    コラム編集ページ
    <%= f.text_field :title, class: "title", placeholder: "タイトル"  %>
    <%= f.text_area :text, class: "text", placeholder: "テキスト", rows: "5", cols: "30" %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "---"}, {class:"genre-select"}) %>
    <%= f.submit "修正する", class:"btn" %>
  </div>
<% end %>

app/views/admin/columns/new.html.erb
<%= render "shared/second_header" %>
<%= form_with url: admin_columns_path, model: @column, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="column-box">
    コラム投稿ページ
    <%= f.text_field :title, class: "title", placeholder: "タイトル"  %>
    <%= f.text_area :text, class: "text", placeholder: "テキスト", rows: "5", cols: "30" %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "---"}, {class:"genre-select"}) %>
    <%= f.submit "投稿する", class:"btn" %>
  </div>
<% end %>

app/views/columns/index.html.erb
<%= render "shared/header" %>

<h2>＜コラム一覧＞</h2>
    <% @columns.each do |f| %>
    <div class="columns">
      <div class="column-title">
        <%= f.title %>
      </div>
      <div class="column-text">
        <%= f.text %>
      </div>
      <div class="column-genre">
        <%= f.genre.name %>
      </div>
      <div class="column-date">
        <%= l f.created_at, format: :short %>
      </div>
      <ul class = column-admin>
        <%# adminの時だけ編集・削除機能を表示する %>
        <% if user_signed_in? && current_user.admin? %>
          <li><%= link_to '編集', edit_admin_column_path(f.id), method: :get, class: "column-edit" %></li>
          <li><%= link_to '削除', admin_column_path(f.id), method: :delete, class: "column-delete" %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

<%= link_to( new_record_path, class: 'record-btn') do %>
  <span class='record-btn-text'>記録する</span>
  <%= image_tag 'My project.png' , size: '185x50' ,class: "record-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/columns/search.html.erb
<%= render "shared/header" %>

<h2>＜コラムの検索一覧＞</h2>
    <% @columns.each do |f| %>
    <div class="columns">
      <div class="column-title">
        <%= f.title %>
      </div>
      <div class="column-text">
        <%= f.text %>
      </div>
      <div class="column-genre">
        <%= f.genre.name %>
      </div>
      <div class="column-date">
        <%= l f.created_at, format: :short %>
      </div>
      <ul class = column-admin>
        <%# adminの時だけ編集・削除機能を表示する %>
        <% if user_signed_in? && current_user.admin? %>
          <li><%= link_to '編集', edit_admin_column_path(f.id), method: :get, class: "column-edit" %></li>
          <li><%= link_to '削除', admin_column_path(f.id), method: :delete, class: "column-delete" %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

<%= link_to("#_path", class: 'record-btn') do %>
  <span class='record-btn-text'>記録する</span>
  <%= image_tag 'My project.png' , size: '185x50' ,class: "record-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# レスポンシブ対応のために表示領域（viewport）を指定する contentで機器のサイズに合わせる記述、拡大率1.0を指定 %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HeartApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# 下記の記述は、app/assets/stylesheets/application.cssというcssファイルを読み込んでいることを示す %>
    <%# application.cssは、*= require_tree .という記述があり、同じディレクトリにあるcssファイルを読み込むことを示す %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/edit.html.erb
<h2> 記録を編集する</h2>
<%= link_to image_tag("My project-6.png", class:"heartapp-icon-6-2"), "/" %>

<%#= new.html.erbと同じ記述 フォームの受け渡し先（urlが異なる）%>
<%= form_with(model: @record, url: record_path, local: true) do |form| %>

  <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="kt">
    <%= form.label :kt %>
    <%= form.text_field :kt, maxlength: 4 %>
  </div>

  <div class="pulse">
    <%= form.label :pulse %>
    <%= form.text_field :pulse, maxlength: 3 %>
  </div>

  <%# 血圧は同じラベル内に収縮期と拡張期のフォームを入力 ラベルは1つ、同じラベル内に記述すると横並びになる。%>
  <div class="bp">
    <%= form.label :bp %>
    <%= form.text_field :systolic, maxlength: 3 %>
    <%= "/" %>
    <%= form.text_field :diastolic, maxlength: 3 %>
  </div>

  <div class="bw">
    <%= form.label :bw %>
    <%= form.text_field :bw, maxlength: 5 %>
  </div>

  <%# ラジオボタンを作成 %>
  <div class="palpitation">
    <%= "動悸" %>
    <%= form.label :palpitation, 'あり', value: 1 %>
    <%= form.radio_button :palpitation, '1' %>
    <%= form.label :palpitation, 'なし', value: 0 %>
    <%= form.radio_button :palpitation, '0' %>
  </div>

  <div class="suffocation">
    <%= "息苦しさ" %>
    <%= form.label :suffocation, 'あり', value: 1 %>
    <%= form.radio_button :suffocation, '1' %>
    <%= form.label :suffocation, 'なし', value: 0 %>
    <%= form.radio_button :suffocation, '0' %>
  </div>

  <div class="swelling">
     <%= "浮腫" %>
    <%= form.label :swelling, 'あり', value: 1 %>
    <%= form.radio_button :swelling, '1' %>
    <%= form.label :swelling, 'なし', value: 0 %>
    <%= form.radio_button :swelling, '0' %>
  </div>

  <div class="fatigue">
    <%= "倦怠感" %>
    <%= form.label :fatigue, 'あり', value: 1 %>
    <%= form.radio_button :fatigue, '1' %>
    <%= form.label :fatigue, 'なし', value: 0 %>
    <%= form.radio_button :fatigue, '0' %>
  </div>

  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>
<%= link_to 'カレンダーへ戻る', records_path %> 

app/views/records/index.html.erb
<h2> 記録カレンダー</h2>
<%= link_to image_tag("My project-6.png", class:"heartapp-icon-6-2"), "/" %>

<br>
  <% if user_signed_in? %>
    <%= link_to current_user.nickname, "#", class: "user-nickname" %><%= "さんの、" %>
    <%= "目標体重は "%>
    <%= current_user.target_weight %><%= "kg" %>
  <% end %>

<%= month_calendar events: @records do |date, records| %>
  <%= date.day %>

  <% records.each do |record| %>
    <div>
      <%= link_to record.bw, record %>  <%# 今は体重を表示させる、今後外来予約入力ができるようになれば入力表示内容を検討する%>
    </div>
  <% end %>
<% end %>

<%= link_to( new_record_path, class: 'record-btn') do %>
  <span class='record-btn-text'>記録する</span>
  <%= image_tag 'My project.png' , size: '185x50' ,class: "record-btn-icon" %>
<% end %>

app/views/records/new.html.erb
<h2> 記録を入力する</h2>
<%= link_to image_tag("My project-6.png", class:"heartapp-icon-6-2"), "/" %>

<%= form_with(model: @record, url: records_path, local: true) do |form| %>

  <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="kt">
    <%= form.label :kt %>
    <%= form.text_field :kt, maxlength: 4 %>
  </div>

  <div class="pulse">
    <%= form.label :pulse %>
    <%= form.text_field :pulse, maxlength: 3 %>
  </div>

  <%# 血圧は同じラベル内に収縮期と拡張期のフォームを入力 ラベルは1つ、同じラベル内に記述すると横並びになる。%>
  <div class="bp">
    <%= form.label :bp %>
    <%= form.text_field :systolic, maxlength: 3 %>
    <%= "/" %>
    <%= form.text_field :diastolic, maxlength: 3 %>
  </div>

  <div class="bw">
    <%= form.label :bw %>
    <%= form.text_field :bw, maxlength: 5 %>
  </div>

  <%# ラジオボタンを作成 %>
  <div class="palpitation">
    <%= "動悸" %>
    <%= form.label :palpitation, 'あり', value: 1 %>
    <%= form.radio_button :palpitation, '1' %>
    <%= form.label :palpitation, 'なし', value: 0 %>
    <%= form.radio_button :palpitation, '0' %>
  </div>

  <div class="suffocation">
    <%= "息苦しさ" %>
    <%= form.label :suffocation, 'あり', value: 1 %>
    <%= form.radio_button :suffocation, '1' %>
    <%= form.label :suffocation, 'なし', value: 0 %>
    <%= form.radio_button :suffocation, '0' %>
  </div>

  <div class="swelling">
     <%= "浮腫" %>
    <%= form.label :swelling, 'あり', value: 1 %>
    <%= form.radio_button :swelling, '1' %>
    <%= form.label :swelling, 'なし', value: 0 %>
    <%= form.radio_button :swelling, '0' %>
  </div>

  <div class="fatigue">
    <%= "倦怠感" %>
    <%= form.label :fatigue, 'あり', value: 1 %>
    <%= form.radio_button :fatigue, '1' %>
    <%= form.label :fatigue, 'なし', value: 0 %>
    <%= form.radio_button :fatigue, '0' %>
  </div>

  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>
<%= link_to 'カレンダーへ戻る', records_path %> 

app/views/records/show.html.erb
<h2> 記録の詳細</h2>
<%= link_to image_tag("My project-6.png", class:"heartapp-icon-6-2"), "/" %>
<%# 時間は表記しなくてよいので↓日付のみ 時間が必要なら  %H:%M を追記 ("%Y-%m-%d %H:%M")へ%>
<p>
  <strong>記録日</strong> 
  <%= @record.start_time.strftime("%Y-%m-%d") %>
</p>

<p>
  <strong>体温</strong>
  <%= @record.kt %>
  <%= "℃" %>
</p>

<p>
  <strong>脈拍</strong>
  <%= @record.pulse %>
  <%= "回/分" %>
</p>

<p>
  <strong>血圧</strong>
  <%= @record.systolic %><%="/"%><%= @record.diastolic %>
  <%= "mmHg" %>
</p>

<p>
  <strong>体重</strong>
  <%= @record.bw %>
  <%= "kg" %>
</p>

<%# 動悸以降はfalse表示になってしまうため各if文で表示切り替え %>
<p>
  <strong>動悸</strong>
  <% if @record.palpitation == true %>
    <%= "あり" %>
    <br>
    <%= " まずは安静にしましょう。自己検脈をしリズム不整がある、気分がよくならないことが続けば受診をしましょう" %>
  <% else %>
    <%= "なし" %>
  <% end %>
</p>

<p>
  <strong>息苦しさ</strong>
  <% if @record.suffocation == true %>
    <%= "あり" %>
    <br>
    <%= " どの程度の息切れがしますか？ 休んでもよくならない、横になって寝れない（座りながら寝る）ときには受診しましょう" %>
  <% else %>
    <%= "なし" %>
  <% end %>
</p>

<p>
  <strong>浮腫</strong>
  <% if @record.swelling == true %>
    <%= "あり" %>
    <br>
    <%= " 体重は増加していませんか？ 目標体重＋2kg以上あるときには、外来予約を待たずに受診しましょう" %>
  <% else %>
    <%= "なし" %>
  <% end %>
</p>

<p>
  <strong>倦怠感</strong>
  <% if @record.fatigue == true %>
    <%= "あり" %>
    <br>
    <%= " だるさ、疲れやすさに加えて、食欲不振はありませんか？ 心不全増悪のリスクがあります。続くようなら受診しましょう" %>
  <% else %>
    <%= "なし" %>
  <% end %>
</p>

<%= link_to '編集', edit_record_path(@record) %> 
<%#= data: { confirm: 'Are you sure?' }はブラウザのアラート機能を利用 他にいい方法はないか？%>
<%= link_to '削除', record_path(@record), method: :delete, data: { confirm: '削除しますか?' } %> 
<%= link_to 'カレンダーへ戻る', records_path %> 

app/views/shared/_error_messages.html.erb
<%# どのモデルのバリデーションにも対応できるように、if文にmodel.errors.any? を記述 %>
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# CSS・・・assets/stylesheets/shared/footer.css %>
<footer class='footer'>
  <p>© HeartApp</p>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("My project-6.png", class:"heartapp-icon-6"), "/" %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li>
        <div class="search-field">
          <%= search_form_for Column.ransack(params[:q]), url: search_columns_path do |f| %>
          <%= f.label :genre_id_eq, 'コラムのカテゴリー', class: "category-list"  %>
          <br>
          <%= f.collection_select(:genre_id_eq,  Genre.all, :id, :name, {include_blank: "---"},{class:"genre-select-top"}) %>
        </div>
        <%= f.submit '検索' %>
        <% end %>
      </li>
      <li><%= link_to 'カレンダー', records_path, class: "calendar-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>  
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %> 
      <% if user_signed_in? && current_user.admin? %>
        <li><%= link_to 'コラム投稿', new_admin_column_path, class:"post" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second_header.html.erb
<%# CSS・・・assets/stylesheets/shared/second-header.css %>
<header class='second-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("My project-5.png", class:"heartapp-icon-5"), "/" %>
  </div>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>